# Compose file for Online Daily Work Schedule

services:
  js-backend:
    build:
      context: ./work-schedule-app/backend
    container_name: js-backend
    restart: unless-stopped
    init: true
    # Define environment variables here
    environment:
      - DB_HOST=mariadb
      - DB_USER=work_user # Matches mariadb service
      - DB_PASSWORD=yourpasswordofchoice # Matches mariadb service
      - DB_NAME=work_schedule # Matches mariadb service
      - NODE_ENV=production # Good practice to set explicitly
      # Add other necessary env vars like SESSION_SECRET, FRONTEND_URL if needed
      - SESSION_SECRET=replace_with_a_real_secret_in_production
      - FRONTEND_URL=http://localhost:4173 # Or the external URL
    ports:
      - "3001:3001"
    depends_on:
      mariadb: # Use long syntax for healthcheck dependency
        condition: service_healthy
    networks:
      - appnet
    # The backend expects a MariaDB database, see README for .env setup

  js-frontend:
    build:
      context: ./work-schedule-frontend-new
      #dockerfile: ../work-schedule-frontend-newDockerfile
    container_name: js-frontend
    restart: unless-stopped
    init: true
    ports:
      - "4173:4173"
    networks:
      - appnet
    depends_on:
      - js-backend
    # env_file: ./.env  # Uncomment if .env file exists in frontend directory

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: work_schedule
      MYSQL_USER: work_user
      MYSQL_PASSWORD: yourpasswordofchoice # <-- Use a strong password
      MYSQL_ROOT_PASSWORD: changeme # <-- Use a strong password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/initdb:/docker-entrypoint-initdb.d # <-- Corrected path
    healthcheck:
      # Use CMD-SHELL for better variable interpolation
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p\"$${MYSQL_ROOT_PASSWORD}\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - appnet
    # The database credentials should match those in your .env file

networks:
  appnet:
    driver: bridge

volumes:
  mariadb_data: {} # Define the named volume here (empty mapping is fine)
